version: "3"
services:
  nexus:
    image: 'sonatype/nexus3:latest'
    container_name: 'nexus'
    restart: unless-stopped
    ports: 
      - '8082:8081'
    volumes:
      - ./data/nexus-data:/var/nexus-data