version: '3'
services:
  jenkins:
    image: 'jenkinsci/blueocean:latest'
    container_name: 'jenkins'
    restart: unless-stopped
    user: root
    ports: 
      - '8081:8080'
      - '50001:50000'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.m2/repository:/root/.m2/repository
      - /opt/env:/opt/env